const OWNED_BOOKS = [
  { title: "The Invisible Life of Addie LaRue", author: "V.E. Schwab", genre: "Fantasy", status: "read" },
  { title: "Blue Sisters", author: "Coco Mellors", genre: "Literary Fiction", status: "read" },
  { title: "Great Big Beautiful Life", author: "Emily Henry", genre: "Romance", status: "read" },
  { title: "People We Meet on Vacation", author: "Emily Henry", genre: "Romance", status: "read" },
  { title: "Book Lovers", author: "Emily Henry", genre: "Romance", status: "read" },
  { title: "Beach Read", author: "Emily Henry", genre: "Romance", status: "read" },
  { title: "Love on the Brain", author: "Ali Hazelwood", genre: "Romance", status: "read" },
  { title: "Bride", author: "Ali Hazelwood", genre: "Romance", status: "read" },
  { title: "Mate", author: "Ali Hazelwood", genre: "Romance", status: "read" },
  { title: "The Dead Romantics", author: "Ashley Poston", genre: "Romance", status: "read" },
  { title: "Selected Poems", author: "Emily Dickinson", genre: "Poetry", status: "read" },
  { title: "Rebecca", author: "Daphne du Maurier", genre: "Gothic Fiction", status: "read" },
  { title: "Vladimir", author: "Julia May Jonas", genre: "Literary Fiction", status: "read" },
  { title: "Sour Cherry", author: "Natalia Theodoridou", genre: "Literary Fiction", status: "read" },
  { title: "The Hounding", author: "Xenobe Purvis", genre: "Literary Fiction", status: "read" },
  { title: "Villette", author: "Charlotte Brontë", genre: "Classic", status: "read" },
  { title: "The Tenant of Wildfell Hall", author: "Anne Brontë", genre: "Classic", status: "tbr" },
  { title: "Works of Brontë", author: "The Brontës", genre: "Classic", status: "tbr" },
  { title: "We Have Always Lived in the Castle", author: "Shirley Jackson", genre: "Gothic Horror", status: "read" },
  { title: "The Names", author: "Florence Knapp", genre: "Literary Fiction", status: "tbr" },
  { title: "This Story Might Save Your Life", author: "Tiffany Crum", genre: "Literary Fiction", status: "read" },
  { title: "A Constellation of Vital Phenomena", author: "Anthony Marra", genre: "Literary Fiction", status: "tbr" },
  { title: "Yesteryear", author: "Caro Claire Burke", genre: "Literary Fiction", status: "tbr" },
  { title: "Canon", author: "Paige Lewis", genre: "Poetry", status: "tbr" },
  { title: "Antidote", author: "Karen Russell", genre: "Literary Fiction", status: "tbr" },
  { title: "11/22/63", author: "Stephen King", genre: "Horror / Thriller", status: "tbr" },
  { title: "The Likeness", author: "Tana French", genre: "Crime / Thriller", status: "tbr" },
  { title: "Candelaria", author: "Melissa Lozada-Oliva", genre: "Poetry", status: "tbr" },
  { title: "The Bee Sting", author: "Paul Murray", genre: "Literary Fiction", status: "tbr" },
  { title: "The Symposium", author: "Plato", genre: "Classic / Philosophy", status: "tbr" },
  { title: "Girl, Woman, Other", author: "Bernardine Evaristo", genre: "Literary Fiction", status: "read" },
  { title: "Shuggie Bain", author: "Douglas Stuart", genre: "Literary Fiction", status: "read" },
  { title: "The Promise", author: "Damon Galgut", genre: "Literary Fiction", status: "tbr" },
  { title: "The Seven Moons of Maali Almeida", author: "Shehan Karunatilaka", genre: "Literary Fiction", status: "tbr" },
  { title: "Prophet Song", author: "Paul Lynch", genre: "Literary Fiction", status: "read" },
  { title: "Orbital", author: "Samantha Harvey", genre: "Literary Fiction", status: "read" },
  { title: "Flesh", author: "T.C. Boyle", genre: "Literary Fiction", status: "tbr" },
  { title: "Betty", author: "Tiffany McDaniel", genre: "Literary Fiction", status: "read" },
  { title: "The Compound", author: "Aisling Rawle", genre: "Horror", status: "read" },
  { title: "The Dream Hotel", author: "Laila Lalami", genre: "Literary Fiction", status: "read" },
  { title: "Memorial", author: "Bryan Washington", genre: "Literary Fiction", status: "read" },
  { title: "Circe", author: "Madeline Miller", genre: "Fantasy / Mythology", status: "read" },
  { title: "Hamnet", author: "Maggie O'Farrell", genre: "Historical Fiction", status: "read" },
  { title: "A Gentleman in Moscow", author: "Amor Towles", genre: "Historical Fiction", status: "read" },
  { title: "Olga Dies Dreaming", author: "Xochitl Gonzalez", genre: "Literary Fiction", status: "read" },
  { title: "Shark Heart", author: "Emily Habeck", genre: "Literary Fiction", status: "read" },
  { title: "Thistlefoot", author: "GennaRose Nethercott", genre: "Fantasy / Horror", status: "read" },
  { title: "Kaikeyi", author: "Vaishnavi Patel", genre: "Fantasy / Mythology", status: "read" },
  { title: "Notes on Your Sudden Disappearance", author: "Alison Espach", genre: "Literary Fiction", status: "read" },
  { title: "Build Your House Around My Body", author: "Violet Kupersmith", genre: "Horror", status: "read" },
  { title: "A Tale for the Time Being", author: "Ruth Ozeki", genre: "Literary Fiction", status: "read" },
  { title: "Mina's Matchbox", author: "Yoko Ogawa", genre: "Literary Fiction", status: "read" },
  { title: "Butter", author: "Asako Yuzuki", genre: "Literary Fiction", status: "read" },
  { title: "Breasts and Eggs", author: "Mieko Kawakami", genre: "Literary Fiction", status: "read" },
  { title: "Pachinko", author: "Min Jin Lee", genre: "Historical Fiction", status: "read" },
  { title: "Strange Houses", author: "Uketsu", genre: "Horror / Mystery", status: "read" },
  { title: "Strange Pictures", author: "Uketsu", genre: "Horror / Mystery", status: "tbr" },
  { title: "On Earth As It Is Beneath", author: "Ana Paula Maia", genre: "Literary Fiction", status: "read" },
  { title: "Cursed Daughters", author: "Oyinkan Braithwaite", genre: "Literary Fiction", status: "tbr" },
  { title: "Vanishing World", author: "Sayaka Murata", genre: "Literary Fiction", status: "tbr" },
  { title: "Angel Down", author: "Daniel Kraus", genre: "Horror", status: "tbr" },
  { title: "The Vegetarian", author: "Han Kang", genre: "Literary Fiction", status: "read" },
  { title: "We Do Not Part", author: "Han Kang", genre: "Literary Fiction", status: "tbr" },
  { title: "Earthlings", author: "Sayaka Murata", genre: "Literary Fiction", status: "read" },
  { title: "Beautiful Star", author: "Yukio Mishima", genre: "Literary Fiction", status: "tbr" },
  { title: "Welcome to the Hyunam-dong Bookshop", author: "Hwang Bo-reum", genre: "Literary Fiction", status: "tbr" },
  { title: "Uzumaki", author: "Junji Ito", genre: "Horror / Manga", status: "tbr" },
  { title: "Gyo", author: "Junji Ito", genre: "Horror / Manga", status: "tbr" },
  { title: "Grass", author: "Keum Suk Gendry-Kim", genre: "Graphic Novel / History", status: "read" },
  { title: "Tales from the Cafe", author: "Toshikazu Kawaguchi", genre: "Literary Fiction", status: "read" },
  { title: "Vigil", author: "George Saunders", genre: "Short Stories", status: "read" },
  { title: "The Overstory", author: "Richard Powers", genre: "Literary Fiction", status: "tbr" },
  { title: "Time Shelter", author: "Georgi Gospodinov", genre: "Literary Fiction", status: "tbr" },
  { title: "My Work", author: "Olga Ravn", genre: "Literary Fiction", status: "tbr" },
  { title: "Penance", author: "Eliza Clark", genre: "Literary Fiction", status: "read" },
  { title: "The Shadow King", author: "Maaza Mengiste", genre: "Historical Fiction", status: "tbr" },
  { title: "The Wax Child", author: "Olga Ravn", genre: "Literary Fiction", status: "read" },
  { title: "An Earthquake Is a Shaking of the Surface of the Earth", author: "Anna Moschovakis", genre: "Literary Fiction", status: "read" },
  { title: "My Dreadful Body", author: "Diana Fisenbrandt", genre: "Literary Fiction", status: "tbr" },
  { title: "The Radium Girls", author: "Kate Moore", genre: "Nonfiction / History", status: "tbr" },
  { title: "To the Lighthouse", author: "Virginia Woolf", genre: "Classic", status: "tbr" },
  { title: "The Unwomanly Face of War", author: "Svetlana Alexievich", genre: "Nonfiction", status: "read" },
  { title: "Words for War: New Poems from Ukraine", author: "Various", genre: "Poetry", status: "tbr" },
  { title: "The Luminaries", author: "Eleanor Catton", genre: "Historical Fiction", status: "tbr" },
  { title: "Silence", author: "Shusaku Endo", genre: "Historical Fiction", status: "tbr" },
  { title: "Everything Under", author: "Daisy Johnson", genre: "Literary Fiction", status: "tbr" },
  { title: "Once There Were Wolves", author: "Charlotte McConaghy", genre: "Literary Fiction", status: "read" },
  { title: "The Wedding People", author: "Alison Espach", genre: "Literary Fiction", status: "read" },
  { title: "Drive Your Plow Over the Bones of the Dead", author: "Olga Tokarczuk", genre: "Literary Fiction", status: "read" },
  { title: "The Robber Bride", author: "Margaret Atwood", genre: "Literary Fiction", status: "tbr" },
  { title: "The Blind Assassin", author: "Margaret Atwood", genre: "Literary Fiction", status: "read" },
  { title: "Bodily Harm", author: "Margaret Atwood", genre: "Literary Fiction", status: "read" },
  { title: "Alias Grace", author: "Margaret Atwood", genre: "Historical Fiction", status: "read" },
  { title: "Cat's Eye", author: "Margaret Atwood", genre: "Literary Fiction", status: "tbr" },
  { title: "The Handmaid's Tale", author: "Margaret Atwood", genre: "Dystopia", status: "read" },
  { title: "MaddAddam", author: "Margaret Atwood", genre: "Dystopia", status: "read" },
  { title: "White Ivy", author: "Susie Yang", genre: "Thriller", status: "read" },
  { title: "The Chestnut Man", author: "Søren Sveistrup", genre: "Crime / Thriller", status: "tbr" },
  { title: "The Daughters' War", author: "Christopher Buehlman", genre: "Fantasy / Horror", status: "tbr" },
  { title: "The Book of Koli", author: "M.R. Carey", genre: "Dystopia", status: "tbr" },
  { title: "The Chain", author: "Adrian McKinty", genre: "Crime / Thriller", status: "read" },
  { title: "When She Woke", author: "Hillary Jordan", genre: "Dystopia", status: "read" },
  { title: "When the Wolf Comes Home", author: "Nat Cassidy", genre: "Horror", status: "tbr" },
  { title: "Manhunt", author: "Gretchen Felker-Martin", genre: "Horror", status: "tbr" },
  { title: "Tender Is the Flesh", author: "Agustina Bazterrica", genre: "Horror / Dystopia", status: "read" },
  { title: "Reformatory", author: "Tananarive Due", genre: "Horror", status: "tbr" },
  { title: "Our Wives Under the Sea", author: "Julia Armfield", genre: "Horror", status: "tbr" },
  { title: "I Who Have Never Known Men", author: "Jacqueline Harpman", genre: "Dystopia", status: "read" },
  { title: "Bliss Montage", author: "Ling Ma", genre: "Short Stories", status: "tbr" },
  { title: "Fever Dream", author: "Samanta Schweblin", genre: "Horror", status: "tbr" },
  { title: "The Bog Wife", author: "Kay Chronister", genre: "Horror", status: "read" },
  { title: "Carrie", author: "Stephen King", genre: "Horror", status: "tbr" },
  { title: "A Certain Hunger", author: "Chelsea G. Summers", genre: "Horror / Dark Comedy", status: "read" },
  { title: "We Spread", author: "Iain Reid", genre: "Horror", status: "read" },
  { title: "The Push", author: "Ashley Audrain", genre: "Thriller", status: "read" },
  { title: "Gone with the Wind", author: "Margaret Mitchell", genre: "Historical Fiction", status: "read" },
  { title: "We Used to Live Here", author: "Marcus Bagal", genre: "Horror", status: "tbr" },
  { title: "On the Calculation of Volume 3", author: "Solvej Balle", genre: "Literary Fiction", status: "tbr" },
  { title: "TB and the Dorians", author: "Nick Cutter", genre: "Horror", status: "reading" },
];
